services:
  mongo:
    container_name: playback-mongo
    image: mongo:7
    network_mode: host
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: childapp

volumes:
  mongo-data:
